//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPrestadores.Services.SigmepOda {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCrearOda", Namespace="http://schemas.datacontract.org/2004/07/Saludsa.EntidadesTerceros")]
    [System.SerializableAttribute()]
    public partial class RespuestaCrearOda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaCaducidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaEmisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroOrdenAtencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenConfirmacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((this.CodigoErrorField.Equals(value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaCaducidad {
            get {
                return this.FechaCaducidadField;
            }
            set {
                if ((this.FechaCaducidadField.Equals(value) != true)) {
                    this.FechaCaducidadField = value;
                    this.RaisePropertyChanged("FechaCaducidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaEmision {
            get {
                return this.FechaEmisionField;
            }
            set {
                if ((this.FechaEmisionField.Equals(value) != true)) {
                    this.FechaEmisionField = value;
                    this.RaisePropertyChanged("FechaEmision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroOrdenAtencion {
            get {
                return this.NumeroOrdenAtencionField;
            }
            set {
                if ((this.NumeroOrdenAtencionField.Equals(value) != true)) {
                    this.NumeroOrdenAtencionField = value;
                    this.RaisePropertyChanged("NumeroOrdenAtencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenConfirmacion {
            get {
                return this.TokenConfirmacionField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenConfirmacionField, value) != true)) {
                    this.TokenConfirmacionField = value;
                    this.RaisePropertyChanged("TokenConfirmacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenAtencion", Namespace="http://schemas.datacontract.org/2004/07/Saludsa.EntidadesTerceros")]
    [System.SerializableAttribute()]
    public partial class OrdenAtencion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosBeneficiarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosTitularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CodigoContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoEspecialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CodigoEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EmiteOdasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsPrestadorAfiliadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EspecialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaCaducidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaEmisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NivelContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NivelPrestadorDesdeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NivelPrestadorHastaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreBeneficiarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrePrestadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresBeneficiarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresTitularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDocumentoBeneficiarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDocumentoTitularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroOrdenAtencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoBeneficiarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoTitularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenConfirmacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorAdministrativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorCoberturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorCopagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorCubiertoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorPagarPrestadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidosBeneficiario {
            get {
                return this.ApellidosBeneficiarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosBeneficiarioField, value) != true)) {
                    this.ApellidosBeneficiarioField = value;
                    this.RaisePropertyChanged("ApellidosBeneficiario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidosTitular {
            get {
                return this.ApellidosTitularField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosTitularField, value) != true)) {
                    this.ApellidosTitularField = value;
                    this.RaisePropertyChanged("ApellidosTitular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CodigoContrato {
            get {
                return this.CodigoContratoField;
            }
            set {
                if ((this.CodigoContratoField.Equals(value) != true)) {
                    this.CodigoContratoField = value;
                    this.RaisePropertyChanged("CodigoContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoEspecialidad {
            get {
                return this.CodigoEspecialidadField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoEspecialidadField, value) != true)) {
                    this.CodigoEspecialidadField = value;
                    this.RaisePropertyChanged("CodigoEspecialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CodigoEstado {
            get {
                return this.CodigoEstadoField;
            }
            set {
                if ((this.CodigoEstadoField.Equals(value) != true)) {
                    this.CodigoEstadoField = value;
                    this.RaisePropertyChanged("CodigoEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoProducto {
            get {
                return this.CodigoProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoProductoField, value) != true)) {
                    this.CodigoProductoField = value;
                    this.RaisePropertyChanged("CodigoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EmiteOdas {
            get {
                return this.EmiteOdasField;
            }
            set {
                if ((this.EmiteOdasField.Equals(value) != true)) {
                    this.EmiteOdasField = value;
                    this.RaisePropertyChanged("EmiteOdas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsPrestadorAfiliado {
            get {
                return this.EsPrestadorAfiliadoField;
            }
            set {
                if ((this.EsPrestadorAfiliadoField.Equals(value) != true)) {
                    this.EsPrestadorAfiliadoField = value;
                    this.RaisePropertyChanged("EsPrestadorAfiliado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Especialidad {
            get {
                return this.EspecialidadField;
            }
            set {
                if ((object.ReferenceEquals(this.EspecialidadField, value) != true)) {
                    this.EspecialidadField = value;
                    this.RaisePropertyChanged("Especialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaCaducidad {
            get {
                return this.FechaCaducidadField;
            }
            set {
                if ((this.FechaCaducidadField.Equals(value) != true)) {
                    this.FechaCaducidadField = value;
                    this.RaisePropertyChanged("FechaCaducidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaEmision {
            get {
                return this.FechaEmisionField;
            }
            set {
                if ((this.FechaEmisionField.Equals(value) != true)) {
                    this.FechaEmisionField = value;
                    this.RaisePropertyChanged("FechaEmision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short NivelContrato {
            get {
                return this.NivelContratoField;
            }
            set {
                if ((this.NivelContratoField.Equals(value) != true)) {
                    this.NivelContratoField = value;
                    this.RaisePropertyChanged("NivelContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short NivelPrestadorDesde {
            get {
                return this.NivelPrestadorDesdeField;
            }
            set {
                if ((this.NivelPrestadorDesdeField.Equals(value) != true)) {
                    this.NivelPrestadorDesdeField = value;
                    this.RaisePropertyChanged("NivelPrestadorDesde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short NivelPrestadorHasta {
            get {
                return this.NivelPrestadorHastaField;
            }
            set {
                if ((this.NivelPrestadorHastaField.Equals(value) != true)) {
                    this.NivelPrestadorHastaField = value;
                    this.RaisePropertyChanged("NivelPrestadorHasta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreBeneficiario {
            get {
                return this.NombreBeneficiarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreBeneficiarioField, value) != true)) {
                    this.NombreBeneficiarioField = value;
                    this.RaisePropertyChanged("NombreBeneficiario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePrestador {
            get {
                return this.NombrePrestadorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrePrestadorField, value) != true)) {
                    this.NombrePrestadorField = value;
                    this.RaisePropertyChanged("NombrePrestador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombresBeneficiario {
            get {
                return this.NombresBeneficiarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresBeneficiarioField, value) != true)) {
                    this.NombresBeneficiarioField = value;
                    this.RaisePropertyChanged("NombresBeneficiario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombresTitular {
            get {
                return this.NombresTitularField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresTitularField, value) != true)) {
                    this.NombresTitularField = value;
                    this.RaisePropertyChanged("NombresTitular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroContrato {
            get {
                return this.NumeroContratoField;
            }
            set {
                if ((this.NumeroContratoField.Equals(value) != true)) {
                    this.NumeroContratoField = value;
                    this.RaisePropertyChanged("NumeroContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumentoBeneficiario {
            get {
                return this.NumeroDocumentoBeneficiarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDocumentoBeneficiarioField, value) != true)) {
                    this.NumeroDocumentoBeneficiarioField = value;
                    this.RaisePropertyChanged("NumeroDocumentoBeneficiario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumentoTitular {
            get {
                return this.NumeroDocumentoTitularField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDocumentoTitularField, value) != true)) {
                    this.NumeroDocumentoTitularField = value;
                    this.RaisePropertyChanged("NumeroDocumentoTitular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroOrdenAtencion {
            get {
                return this.NumeroOrdenAtencionField;
            }
            set {
                if ((this.NumeroOrdenAtencionField.Equals(value) != true)) {
                    this.NumeroOrdenAtencionField = value;
                    this.RaisePropertyChanged("NumeroOrdenAtencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumentoBeneficiario {
            get {
                return this.TipoDocumentoBeneficiarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoBeneficiarioField, value) != true)) {
                    this.TipoDocumentoBeneficiarioField = value;
                    this.RaisePropertyChanged("TipoDocumentoBeneficiario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumentoTitular {
            get {
                return this.TipoDocumentoTitularField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoTitularField, value) != true)) {
                    this.TipoDocumentoTitularField = value;
                    this.RaisePropertyChanged("TipoDocumentoTitular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenConfirmacion {
            get {
                return this.TokenConfirmacionField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenConfirmacionField, value) != true)) {
                    this.TokenConfirmacionField = value;
                    this.RaisePropertyChanged("TokenConfirmacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorAdministrativo {
            get {
                return this.ValorAdministrativoField;
            }
            set {
                if ((this.ValorAdministrativoField.Equals(value) != true)) {
                    this.ValorAdministrativoField = value;
                    this.RaisePropertyChanged("ValorAdministrativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorCobertura {
            get {
                return this.ValorCoberturaField;
            }
            set {
                if ((this.ValorCoberturaField.Equals(value) != true)) {
                    this.ValorCoberturaField = value;
                    this.RaisePropertyChanged("ValorCobertura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorCopago {
            get {
                return this.ValorCopagoField;
            }
            set {
                if ((this.ValorCopagoField.Equals(value) != true)) {
                    this.ValorCopagoField = value;
                    this.RaisePropertyChanged("ValorCopago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorCubierto {
            get {
                return this.ValorCubiertoField;
            }
            set {
                if ((this.ValorCubiertoField.Equals(value) != true)) {
                    this.ValorCubiertoField = value;
                    this.RaisePropertyChanged("ValorCubierto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorPagarPrestador {
            get {
                return this.ValorPagarPrestadorField;
            }
            set {
                if ((this.ValorPagarPrestadorField.Equals(value) != true)) {
                    this.ValorPagarPrestadorField = value;
                    this.RaisePropertyChanged("ValorPagarPrestador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenPago", Namespace="http://schemas.datacontract.org/2004/07/Saludsa.EntidadesTerceros")]
    [System.SerializableAttribute()]
    public partial class OrdenPago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CodigoEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaGeneracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreBeneficiarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrePrestadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroReclamoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorAdministrativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorCubreSaludField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CodigoEstado {
            get {
                return this.CodigoEstadoField;
            }
            set {
                if ((this.CodigoEstadoField.Equals(value) != true)) {
                    this.CodigoEstadoField = value;
                    this.RaisePropertyChanged("CodigoEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaGeneracion {
            get {
                return this.FechaGeneracionField;
            }
            set {
                if ((this.FechaGeneracionField.Equals(value) != true)) {
                    this.FechaGeneracionField = value;
                    this.RaisePropertyChanged("FechaGeneracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreBeneficiario {
            get {
                return this.NombreBeneficiarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreBeneficiarioField, value) != true)) {
                    this.NombreBeneficiarioField = value;
                    this.RaisePropertyChanged("NombreBeneficiario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePrestador {
            get {
                return this.NombrePrestadorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrePrestadorField, value) != true)) {
                    this.NombrePrestadorField = value;
                    this.RaisePropertyChanged("NombrePrestador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroContrato {
            get {
                return this.NumeroContratoField;
            }
            set {
                if ((this.NumeroContratoField.Equals(value) != true)) {
                    this.NumeroContratoField = value;
                    this.RaisePropertyChanged("NumeroContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroReclamo {
            get {
                return this.NumeroReclamoField;
            }
            set {
                if ((this.NumeroReclamoField.Equals(value) != true)) {
                    this.NumeroReclamoField = value;
                    this.RaisePropertyChanged("NumeroReclamo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorAdministrativo {
            get {
                return this.ValorAdministrativoField;
            }
            set {
                if ((this.ValorAdministrativoField.Equals(value) != true)) {
                    this.ValorAdministrativoField = value;
                    this.RaisePropertyChanged("ValorAdministrativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorCubreSalud {
            get {
                return this.ValorCubreSaludField;
            }
            set {
                if ((this.ValorCubreSaludField.Equals(value) != true)) {
                    this.ValorCubreSaludField = value;
                    this.RaisePropertyChanged("ValorCubreSalud");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValoresConsultaMedica", Namespace="http://schemas.datacontract.org/2004/07/Saludsa.EntidadesTerceros")]
    [System.SerializableAttribute()]
    public partial class ValoresConsultaMedica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NivelesDescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PorcentajeAplicadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PorcentajeDescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PuntosAplicadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorCoberturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorConsultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorCopagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorCubiertoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorPuntoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short NivelesDescuento {
            get {
                return this.NivelesDescuentoField;
            }
            set {
                if ((this.NivelesDescuentoField.Equals(value) != true)) {
                    this.NivelesDescuentoField = value;
                    this.RaisePropertyChanged("NivelesDescuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PorcentajeAplicado {
            get {
                return this.PorcentajeAplicadoField;
            }
            set {
                if ((this.PorcentajeAplicadoField.Equals(value) != true)) {
                    this.PorcentajeAplicadoField = value;
                    this.RaisePropertyChanged("PorcentajeAplicado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PorcentajeDescuento {
            get {
                return this.PorcentajeDescuentoField;
            }
            set {
                if ((this.PorcentajeDescuentoField.Equals(value) != true)) {
                    this.PorcentajeDescuentoField = value;
                    this.RaisePropertyChanged("PorcentajeDescuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PuntosAplicados {
            get {
                return this.PuntosAplicadosField;
            }
            set {
                if ((this.PuntosAplicadosField.Equals(value) != true)) {
                    this.PuntosAplicadosField = value;
                    this.RaisePropertyChanged("PuntosAplicados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorCobertura {
            get {
                return this.ValorCoberturaField;
            }
            set {
                if ((this.ValorCoberturaField.Equals(value) != true)) {
                    this.ValorCoberturaField = value;
                    this.RaisePropertyChanged("ValorCobertura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorConsulta {
            get {
                return this.ValorConsultaField;
            }
            set {
                if ((this.ValorConsultaField.Equals(value) != true)) {
                    this.ValorConsultaField = value;
                    this.RaisePropertyChanged("ValorConsulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorCopago {
            get {
                return this.ValorCopagoField;
            }
            set {
                if ((this.ValorCopagoField.Equals(value) != true)) {
                    this.ValorCopagoField = value;
                    this.RaisePropertyChanged("ValorCopago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorCubierto {
            get {
                return this.ValorCubiertoField;
            }
            set {
                if ((this.ValorCubiertoField.Equals(value) != true)) {
                    this.ValorCubiertoField = value;
                    this.RaisePropertyChanged("ValorCubierto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorPunto {
            get {
                return this.ValorPuntoField;
            }
            set {
                if ((this.ValorPuntoField.Equals(value) != true)) {
                    this.ValorPuntoField = value;
                    this.RaisePropertyChanged("ValorPunto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SigmepOda.IServicioOrdenesAtencion")]
    public interface IServicioOrdenesAtencion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/GuardarAutorizacion", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/GuardarAutorizacionResponse")]
        MvcPrestadores.Services.SigmepOda.RespuestaCrearOda GuardarAutorizacion(int prestadorConvenio, short oficinaLiquidacion, int numeroPersonaBeneficiario, int codigoProcedimiento, long CodigoContrato, string codigoDiagnostico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/GuardarAutorizacion", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/GuardarAutorizacionResponse")]
        System.Threading.Tasks.Task<MvcPrestadores.Services.SigmepOda.RespuestaCrearOda> GuardarAutorizacionAsync(int prestadorConvenio, short oficinaLiquidacion, int numeroPersonaBeneficiario, int codigoProcedimiento, long CodigoContrato, string codigoDiagnostico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/GuardarAutorizacionContactCenter", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/GuardarAutorizacionContactCenterRespo" +
            "nse")]
        MvcPrestadores.Services.SigmepOda.RespuestaCrearOda GuardarAutorizacionContactCenter(int prestadorConvenio, short oficinaLiquidacion, int numeroPersonaBeneficiario, int codigoProcedimiento, long CodigoContrato, string codigoDiagnostico, string nombreUsuario, string emailsAdicionales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/GuardarAutorizacionContactCenter", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/GuardarAutorizacionContactCenterRespo" +
            "nse")]
        System.Threading.Tasks.Task<MvcPrestadores.Services.SigmepOda.RespuestaCrearOda> GuardarAutorizacionContactCenterAsync(int prestadorConvenio, short oficinaLiquidacion, int numeroPersonaBeneficiario, int codigoProcedimiento, long CodigoContrato, string codigoDiagnostico, string nombreUsuario, string emailsAdicionales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/CambiarEstadoOda", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/CambiarEstadoOdaResponse")]
        bool CambiarEstadoOda(int numeroOrdenAtencion, short codigoEstado, long codigoContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/CambiarEstadoOda", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/CambiarEstadoOdaResponse")]
        System.Threading.Tasks.Task<bool> CambiarEstadoOdaAsync(int numeroOrdenAtencion, short codigoEstado, long codigoContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/CambiarDiagnosticoOda", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/CambiarDiagnosticoOdaResponse")]
        bool CambiarDiagnosticoOda(int numeroOrdenAtencion, short codigoEstado, long codigoContrato, string codigoDiagnostico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/CambiarDiagnosticoOda", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/CambiarDiagnosticoOdaResponse")]
        System.Threading.Tasks.Task<bool> CambiarDiagnosticoOdaAsync(int numeroOrdenAtencion, short codigoEstado, long codigoContrato, string codigoDiagnostico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/ObtenerTokenConfirmacion", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/ObtenerTokenConfirmacionResponse")]
        string ObtenerTokenConfirmacion(int numeroReclamo, int numeroPrestador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/ObtenerTokenConfirmacion", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/ObtenerTokenConfirmacionResponse")]
        System.Threading.Tasks.Task<string> ObtenerTokenConfirmacionAsync(int numeroReclamo, int numeroPrestador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesAtencionPorCodigoContra" +
            "to", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesAtencionPorCodigoContra" +
            "toResponse")]
        MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorCodigoContratoResponse ObtenerOrdenesAtencionPorCodigoContrato(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorCodigoContratoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesAtencionPorCodigoContra" +
            "to", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesAtencionPorCodigoContra" +
            "toResponse")]
        System.Threading.Tasks.Task<MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorCodigoContratoResponse> ObtenerOrdenesAtencionPorCodigoContratoAsync(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorCodigoContratoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesAtencionPorNumeroPresta" +
            "dor", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesAtencionPorNumeroPresta" +
            "dorResponse")]
        MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorNumeroPrestadorResponse ObtenerOrdenesAtencionPorNumeroPrestador(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorNumeroPrestadorRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesAtencionPorNumeroPresta" +
            "dor", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesAtencionPorNumeroPresta" +
            "dorResponse")]
        System.Threading.Tasks.Task<MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorNumeroPrestadorResponse> ObtenerOrdenesAtencionPorNumeroPrestadorAsync(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorNumeroPrestadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesAtencionRedSalud", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesAtencionRedSaludRespons" +
            "e")]
        MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionRedSaludResponse ObtenerOrdenesAtencionRedSalud(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionRedSaludRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesAtencionRedSalud", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesAtencionRedSaludRespons" +
            "e")]
        System.Threading.Tasks.Task<MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionRedSaludResponse> ObtenerOrdenesAtencionRedSaludAsync(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionRedSaludRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesAtencionParaPago", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesAtencionParaPagoRespons" +
            "e")]
        MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionParaPagoResponse ObtenerOrdenesAtencionParaPago(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionParaPagoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesAtencionParaPago", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesAtencionParaPagoRespons" +
            "e")]
        System.Threading.Tasks.Task<MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionParaPagoResponse> ObtenerOrdenesAtencionParaPagoAsync(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionParaPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesPagoRedSalud", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesPagoRedSaludResponse")]
        MvcPrestadores.Services.SigmepOda.ObtenerOrdenesPagoRedSaludResponse ObtenerOrdenesPagoRedSalud(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesPagoRedSaludRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesPagoRedSalud", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/ObtenerOrdenesPagoRedSaludResponse")]
        System.Threading.Tasks.Task<MvcPrestadores.Services.SigmepOda.ObtenerOrdenesPagoRedSaludResponse> ObtenerOrdenesPagoRedSaludAsync(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesPagoRedSaludRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/ObtenerValoresConsulta", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/ObtenerValoresConsultaResponse")]
        MvcPrestadores.Services.SigmepOda.ValoresConsultaMedica ObtenerValoresConsulta(string region, string codigoProducto, string codigoPlan, short nivelPrestadorDesde, short nivelPrestadorHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/ObtenerValoresConsulta", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/ObtenerValoresConsultaResponse")]
        System.Threading.Tasks.Task<MvcPrestadores.Services.SigmepOda.ValoresConsultaMedica> ObtenerValoresConsultaAsync(string region, string codigoProducto, string codigoPlan, short nivelPrestadorDesde, short nivelPrestadorHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/ObtenerUrlOda", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/ObtenerUrlOdaResponse")]
        string ObtenerUrlOda(long codigoContrato, int numeroOda, string tokenConfirmacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOrdenesAtencion/ObtenerUrlOda", ReplyAction="http://tempuri.org/IServicioOrdenesAtencion/ObtenerUrlOdaResponse")]
        System.Threading.Tasks.Task<string> ObtenerUrlOdaAsync(long codigoContrato, int numeroOda, string tokenConfirmacion);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerOrdenesAtencionPorCodigoContrato", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerOrdenesAtencionPorCodigoContratoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long codigoContrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public short codigoEstado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int numeroPagina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public short registrosPagina;
        
        public ObtenerOrdenesAtencionPorCodigoContratoRequest() {
        }
        
        public ObtenerOrdenesAtencionPorCodigoContratoRequest(long codigoContrato, short codigoEstado, int numeroPagina, short registrosPagina) {
            this.codigoContrato = codigoContrato;
            this.codigoEstado = codigoEstado;
            this.numeroPagina = numeroPagina;
            this.registrosPagina = registrosPagina;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerOrdenesAtencionPorCodigoContratoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerOrdenesAtencionPorCodigoContratoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MvcPrestadores.Services.SigmepOda.OrdenAtencion[] ObtenerOrdenesAtencionPorCodigoContratoResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int totalRegistros;
        
        public ObtenerOrdenesAtencionPorCodigoContratoResponse() {
        }
        
        public ObtenerOrdenesAtencionPorCodigoContratoResponse(MvcPrestadores.Services.SigmepOda.OrdenAtencion[] ObtenerOrdenesAtencionPorCodigoContratoResult, int totalRegistros) {
            this.ObtenerOrdenesAtencionPorCodigoContratoResult = ObtenerOrdenesAtencionPorCodigoContratoResult;
            this.totalRegistros = totalRegistros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerOrdenesAtencionPorNumeroPrestador", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerOrdenesAtencionPorNumeroPrestadorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int numeroPrestador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public short codigoEstado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int numeroPagina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public short registrosPagina;
        
        public ObtenerOrdenesAtencionPorNumeroPrestadorRequest() {
        }
        
        public ObtenerOrdenesAtencionPorNumeroPrestadorRequest(int numeroPrestador, short codigoEstado, int numeroPagina, short registrosPagina) {
            this.numeroPrestador = numeroPrestador;
            this.codigoEstado = codigoEstado;
            this.numeroPagina = numeroPagina;
            this.registrosPagina = registrosPagina;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerOrdenesAtencionPorNumeroPrestadorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerOrdenesAtencionPorNumeroPrestadorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MvcPrestadores.Services.SigmepOda.OrdenAtencion[] ObtenerOrdenesAtencionPorNumeroPrestadorResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int totalRegistros;
        
        public ObtenerOrdenesAtencionPorNumeroPrestadorResponse() {
        }
        
        public ObtenerOrdenesAtencionPorNumeroPrestadorResponse(MvcPrestadores.Services.SigmepOda.OrdenAtencion[] ObtenerOrdenesAtencionPorNumeroPrestadorResult, int totalRegistros) {
            this.ObtenerOrdenesAtencionPorNumeroPrestadorResult = ObtenerOrdenesAtencionPorNumeroPrestadorResult;
            this.totalRegistros = totalRegistros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerOrdenesAtencionRedSalud", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerOrdenesAtencionRedSaludRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int numeroReclamo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string identificacionTitular;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string identificacionBeneficiario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int numeroConvenio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public short[] codigoEstado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string nombreUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int numeroPagina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public short registrosPagina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public System.Nullable<System.DateTime> fechaDesde;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public System.Nullable<System.DateTime> fechaHasta;
        
        public ObtenerOrdenesAtencionRedSaludRequest() {
        }
        
        public ObtenerOrdenesAtencionRedSaludRequest(int numeroReclamo, string identificacionTitular, string identificacionBeneficiario, int numeroConvenio, short[] codigoEstado, string nombreUsuario, int numeroPagina, short registrosPagina, System.Nullable<System.DateTime> fechaDesde, System.Nullable<System.DateTime> fechaHasta) {
            this.numeroReclamo = numeroReclamo;
            this.identificacionTitular = identificacionTitular;
            this.identificacionBeneficiario = identificacionBeneficiario;
            this.numeroConvenio = numeroConvenio;
            this.codigoEstado = codigoEstado;
            this.nombreUsuario = nombreUsuario;
            this.numeroPagina = numeroPagina;
            this.registrosPagina = registrosPagina;
            this.fechaDesde = fechaDesde;
            this.fechaHasta = fechaHasta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerOrdenesAtencionRedSaludResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerOrdenesAtencionRedSaludResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MvcPrestadores.Services.SigmepOda.OrdenAtencion[] ObtenerOrdenesAtencionRedSaludResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int totalRegistros;
        
        public ObtenerOrdenesAtencionRedSaludResponse() {
        }
        
        public ObtenerOrdenesAtencionRedSaludResponse(MvcPrestadores.Services.SigmepOda.OrdenAtencion[] ObtenerOrdenesAtencionRedSaludResult, int totalRegistros) {
            this.ObtenerOrdenesAtencionRedSaludResult = ObtenerOrdenesAtencionRedSaludResult;
            this.totalRegistros = totalRegistros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerOrdenesAtencionParaPago", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerOrdenesAtencionParaPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int numeroConvenio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public short codigoEstadoOda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public short codigoEstadoOrdenPago;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int numeroPagina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public short registrosPagina;
        
        public ObtenerOrdenesAtencionParaPagoRequest() {
        }
        
        public ObtenerOrdenesAtencionParaPagoRequest(int numeroConvenio, short codigoEstadoOda, short codigoEstadoOrdenPago, int numeroPagina, short registrosPagina) {
            this.numeroConvenio = numeroConvenio;
            this.codigoEstadoOda = codigoEstadoOda;
            this.codigoEstadoOrdenPago = codigoEstadoOrdenPago;
            this.numeroPagina = numeroPagina;
            this.registrosPagina = registrosPagina;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerOrdenesAtencionParaPagoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerOrdenesAtencionParaPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MvcPrestadores.Services.SigmepOda.OrdenAtencion[] ObtenerOrdenesAtencionParaPagoResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int totalRegistros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public decimal totalValorPago;
        
        public ObtenerOrdenesAtencionParaPagoResponse() {
        }
        
        public ObtenerOrdenesAtencionParaPagoResponse(MvcPrestadores.Services.SigmepOda.OrdenAtencion[] ObtenerOrdenesAtencionParaPagoResult, int totalRegistros, decimal totalValorPago) {
            this.ObtenerOrdenesAtencionParaPagoResult = ObtenerOrdenesAtencionParaPagoResult;
            this.totalRegistros = totalRegistros;
            this.totalValorPago = totalValorPago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerOrdenesPagoRedSalud", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerOrdenesPagoRedSaludRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int numeroPagina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public short registrosPagina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int numeroOrdenPago;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int numeroConvenio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int numeroReclamo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public short codigoEstado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public System.Nullable<System.DateTime> fechaDesde;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public System.Nullable<System.DateTime> fechaHasta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public bool tieneDiagnostico;
        
        public ObtenerOrdenesPagoRedSaludRequest() {
        }
        
        public ObtenerOrdenesPagoRedSaludRequest(int numeroPagina, short registrosPagina, int numeroOrdenPago, int numeroConvenio, int numeroReclamo, short codigoEstado, System.Nullable<System.DateTime> fechaDesde, System.Nullable<System.DateTime> fechaHasta, bool tieneDiagnostico) {
            this.numeroPagina = numeroPagina;
            this.registrosPagina = registrosPagina;
            this.numeroOrdenPago = numeroOrdenPago;
            this.numeroConvenio = numeroConvenio;
            this.numeroReclamo = numeroReclamo;
            this.codigoEstado = codigoEstado;
            this.fechaDesde = fechaDesde;
            this.fechaHasta = fechaHasta;
            this.tieneDiagnostico = tieneDiagnostico;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerOrdenesPagoRedSaludResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerOrdenesPagoRedSaludResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MvcPrestadores.Services.SigmepOda.OrdenPago[] ObtenerOrdenesPagoRedSaludResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int totalRegistros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public decimal totalValorPago;
        
        public ObtenerOrdenesPagoRedSaludResponse() {
        }
        
        public ObtenerOrdenesPagoRedSaludResponse(MvcPrestadores.Services.SigmepOda.OrdenPago[] ObtenerOrdenesPagoRedSaludResult, int totalRegistros, decimal totalValorPago) {
            this.ObtenerOrdenesPagoRedSaludResult = ObtenerOrdenesPagoRedSaludResult;
            this.totalRegistros = totalRegistros;
            this.totalValorPago = totalValorPago;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioOrdenesAtencionChannel : MvcPrestadores.Services.SigmepOda.IServicioOrdenesAtencion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioOrdenesAtencionClient : System.ServiceModel.ClientBase<MvcPrestadores.Services.SigmepOda.IServicioOrdenesAtencion>, MvcPrestadores.Services.SigmepOda.IServicioOrdenesAtencion {
        
        public ServicioOrdenesAtencionClient() {
        }
        
        public ServicioOrdenesAtencionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioOrdenesAtencionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioOrdenesAtencionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioOrdenesAtencionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MvcPrestadores.Services.SigmepOda.RespuestaCrearOda GuardarAutorizacion(int prestadorConvenio, short oficinaLiquidacion, int numeroPersonaBeneficiario, int codigoProcedimiento, long CodigoContrato, string codigoDiagnostico) {
            return base.Channel.GuardarAutorizacion(prestadorConvenio, oficinaLiquidacion, numeroPersonaBeneficiario, codigoProcedimiento, CodigoContrato, codigoDiagnostico);
        }
        
        public System.Threading.Tasks.Task<MvcPrestadores.Services.SigmepOda.RespuestaCrearOda> GuardarAutorizacionAsync(int prestadorConvenio, short oficinaLiquidacion, int numeroPersonaBeneficiario, int codigoProcedimiento, long CodigoContrato, string codigoDiagnostico) {
            return base.Channel.GuardarAutorizacionAsync(prestadorConvenio, oficinaLiquidacion, numeroPersonaBeneficiario, codigoProcedimiento, CodigoContrato, codigoDiagnostico);
        }
        
        public MvcPrestadores.Services.SigmepOda.RespuestaCrearOda GuardarAutorizacionContactCenter(int prestadorConvenio, short oficinaLiquidacion, int numeroPersonaBeneficiario, int codigoProcedimiento, long CodigoContrato, string codigoDiagnostico, string nombreUsuario, string emailsAdicionales) {
            return base.Channel.GuardarAutorizacionContactCenter(prestadorConvenio, oficinaLiquidacion, numeroPersonaBeneficiario, codigoProcedimiento, CodigoContrato, codigoDiagnostico, nombreUsuario, emailsAdicionales);
        }
        
        public System.Threading.Tasks.Task<MvcPrestadores.Services.SigmepOda.RespuestaCrearOda> GuardarAutorizacionContactCenterAsync(int prestadorConvenio, short oficinaLiquidacion, int numeroPersonaBeneficiario, int codigoProcedimiento, long CodigoContrato, string codigoDiagnostico, string nombreUsuario, string emailsAdicionales) {
            return base.Channel.GuardarAutorizacionContactCenterAsync(prestadorConvenio, oficinaLiquidacion, numeroPersonaBeneficiario, codigoProcedimiento, CodigoContrato, codigoDiagnostico, nombreUsuario, emailsAdicionales);
        }
        
        public bool CambiarEstadoOda(int numeroOrdenAtencion, short codigoEstado, long codigoContrato) {
            return base.Channel.CambiarEstadoOda(numeroOrdenAtencion, codigoEstado, codigoContrato);
        }
        
        public System.Threading.Tasks.Task<bool> CambiarEstadoOdaAsync(int numeroOrdenAtencion, short codigoEstado, long codigoContrato) {
            return base.Channel.CambiarEstadoOdaAsync(numeroOrdenAtencion, codigoEstado, codigoContrato);
        }
        
        public bool CambiarDiagnosticoOda(int numeroOrdenAtencion, short codigoEstado, long codigoContrato, string codigoDiagnostico) {
            return base.Channel.CambiarDiagnosticoOda(numeroOrdenAtencion, codigoEstado, codigoContrato, codigoDiagnostico);
        }
        
        public System.Threading.Tasks.Task<bool> CambiarDiagnosticoOdaAsync(int numeroOrdenAtencion, short codigoEstado, long codigoContrato, string codigoDiagnostico) {
            return base.Channel.CambiarDiagnosticoOdaAsync(numeroOrdenAtencion, codigoEstado, codigoContrato, codigoDiagnostico);
        }
        
        public string ObtenerTokenConfirmacion(int numeroReclamo, int numeroPrestador) {
            return base.Channel.ObtenerTokenConfirmacion(numeroReclamo, numeroPrestador);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerTokenConfirmacionAsync(int numeroReclamo, int numeroPrestador) {
            return base.Channel.ObtenerTokenConfirmacionAsync(numeroReclamo, numeroPrestador);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorCodigoContratoResponse MvcPrestadores.Services.SigmepOda.IServicioOrdenesAtencion.ObtenerOrdenesAtencionPorCodigoContrato(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorCodigoContratoRequest request) {
            return base.Channel.ObtenerOrdenesAtencionPorCodigoContrato(request);
        }
        
        public MvcPrestadores.Services.SigmepOda.OrdenAtencion[] ObtenerOrdenesAtencionPorCodigoContrato(long codigoContrato, short codigoEstado, int numeroPagina, short registrosPagina, out int totalRegistros) {
            MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorCodigoContratoRequest inValue = new MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorCodigoContratoRequest();
            inValue.codigoContrato = codigoContrato;
            inValue.codigoEstado = codigoEstado;
            inValue.numeroPagina = numeroPagina;
            inValue.registrosPagina = registrosPagina;
            MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorCodigoContratoResponse retVal = ((MvcPrestadores.Services.SigmepOda.IServicioOrdenesAtencion)(this)).ObtenerOrdenesAtencionPorCodigoContrato(inValue);
            totalRegistros = retVal.totalRegistros;
            return retVal.ObtenerOrdenesAtencionPorCodigoContratoResult;
        }
        
        public System.Threading.Tasks.Task<MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorCodigoContratoResponse> ObtenerOrdenesAtencionPorCodigoContratoAsync(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorCodigoContratoRequest request) {
            return base.Channel.ObtenerOrdenesAtencionPorCodigoContratoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorNumeroPrestadorResponse MvcPrestadores.Services.SigmepOda.IServicioOrdenesAtencion.ObtenerOrdenesAtencionPorNumeroPrestador(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorNumeroPrestadorRequest request) {
            return base.Channel.ObtenerOrdenesAtencionPorNumeroPrestador(request);
        }
        
        public MvcPrestadores.Services.SigmepOda.OrdenAtencion[] ObtenerOrdenesAtencionPorNumeroPrestador(int numeroPrestador, short codigoEstado, int numeroPagina, short registrosPagina, out int totalRegistros) {
            MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorNumeroPrestadorRequest inValue = new MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorNumeroPrestadorRequest();
            inValue.numeroPrestador = numeroPrestador;
            inValue.codigoEstado = codigoEstado;
            inValue.numeroPagina = numeroPagina;
            inValue.registrosPagina = registrosPagina;
            MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorNumeroPrestadorResponse retVal = ((MvcPrestadores.Services.SigmepOda.IServicioOrdenesAtencion)(this)).ObtenerOrdenesAtencionPorNumeroPrestador(inValue);
            totalRegistros = retVal.totalRegistros;
            return retVal.ObtenerOrdenesAtencionPorNumeroPrestadorResult;
        }
        
        public System.Threading.Tasks.Task<MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorNumeroPrestadorResponse> ObtenerOrdenesAtencionPorNumeroPrestadorAsync(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionPorNumeroPrestadorRequest request) {
            return base.Channel.ObtenerOrdenesAtencionPorNumeroPrestadorAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionRedSaludResponse MvcPrestadores.Services.SigmepOda.IServicioOrdenesAtencion.ObtenerOrdenesAtencionRedSalud(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionRedSaludRequest request) {
            return base.Channel.ObtenerOrdenesAtencionRedSalud(request);
        }
        
        public MvcPrestadores.Services.SigmepOda.OrdenAtencion[] ObtenerOrdenesAtencionRedSalud(int numeroReclamo, string identificacionTitular, string identificacionBeneficiario, int numeroConvenio, short[] codigoEstado, string nombreUsuario, int numeroPagina, short registrosPagina, System.Nullable<System.DateTime> fechaDesde, System.Nullable<System.DateTime> fechaHasta, out int totalRegistros) {
            MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionRedSaludRequest inValue = new MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionRedSaludRequest();
            inValue.numeroReclamo = numeroReclamo;
            inValue.identificacionTitular = identificacionTitular;
            inValue.identificacionBeneficiario = identificacionBeneficiario;
            inValue.numeroConvenio = numeroConvenio;
            inValue.codigoEstado = codigoEstado;
            inValue.nombreUsuario = nombreUsuario;
            inValue.numeroPagina = numeroPagina;
            inValue.registrosPagina = registrosPagina;
            inValue.fechaDesde = fechaDesde;
            inValue.fechaHasta = fechaHasta;
            MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionRedSaludResponse retVal = ((MvcPrestadores.Services.SigmepOda.IServicioOrdenesAtencion)(this)).ObtenerOrdenesAtencionRedSalud(inValue);
            totalRegistros = retVal.totalRegistros;
            return retVal.ObtenerOrdenesAtencionRedSaludResult;
        }
        
        public System.Threading.Tasks.Task<MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionRedSaludResponse> ObtenerOrdenesAtencionRedSaludAsync(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionRedSaludRequest request) {
            return base.Channel.ObtenerOrdenesAtencionRedSaludAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionParaPagoResponse MvcPrestadores.Services.SigmepOda.IServicioOrdenesAtencion.ObtenerOrdenesAtencionParaPago(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionParaPagoRequest request) {
            return base.Channel.ObtenerOrdenesAtencionParaPago(request);
        }
        
        public MvcPrestadores.Services.SigmepOda.OrdenAtencion[] ObtenerOrdenesAtencionParaPago(int numeroConvenio, short codigoEstadoOda, short codigoEstadoOrdenPago, int numeroPagina, short registrosPagina, out int totalRegistros, out decimal totalValorPago) {
            MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionParaPagoRequest inValue = new MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionParaPagoRequest();
            inValue.numeroConvenio = numeroConvenio;
            inValue.codigoEstadoOda = codigoEstadoOda;
            inValue.codigoEstadoOrdenPago = codigoEstadoOrdenPago;
            inValue.numeroPagina = numeroPagina;
            inValue.registrosPagina = registrosPagina;
            MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionParaPagoResponse retVal = ((MvcPrestadores.Services.SigmepOda.IServicioOrdenesAtencion)(this)).ObtenerOrdenesAtencionParaPago(inValue);
            totalRegistros = retVal.totalRegistros;
            totalValorPago = retVal.totalValorPago;
            return retVal.ObtenerOrdenesAtencionParaPagoResult;
        }
        
        public System.Threading.Tasks.Task<MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionParaPagoResponse> ObtenerOrdenesAtencionParaPagoAsync(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesAtencionParaPagoRequest request) {
            return base.Channel.ObtenerOrdenesAtencionParaPagoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcPrestadores.Services.SigmepOda.ObtenerOrdenesPagoRedSaludResponse MvcPrestadores.Services.SigmepOda.IServicioOrdenesAtencion.ObtenerOrdenesPagoRedSalud(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesPagoRedSaludRequest request) {
            return base.Channel.ObtenerOrdenesPagoRedSalud(request);
        }
        
        public MvcPrestadores.Services.SigmepOda.OrdenPago[] ObtenerOrdenesPagoRedSalud(int numeroPagina, short registrosPagina, int numeroOrdenPago, int numeroConvenio, int numeroReclamo, short codigoEstado, System.Nullable<System.DateTime> fechaDesde, System.Nullable<System.DateTime> fechaHasta, bool tieneDiagnostico, out int totalRegistros, out decimal totalValorPago) {
            MvcPrestadores.Services.SigmepOda.ObtenerOrdenesPagoRedSaludRequest inValue = new MvcPrestadores.Services.SigmepOda.ObtenerOrdenesPagoRedSaludRequest();
            inValue.numeroPagina = numeroPagina;
            inValue.registrosPagina = registrosPagina;
            inValue.numeroOrdenPago = numeroOrdenPago;
            inValue.numeroConvenio = numeroConvenio;
            inValue.numeroReclamo = numeroReclamo;
            inValue.codigoEstado = codigoEstado;
            inValue.fechaDesde = fechaDesde;
            inValue.fechaHasta = fechaHasta;
            inValue.tieneDiagnostico = tieneDiagnostico;
            MvcPrestadores.Services.SigmepOda.ObtenerOrdenesPagoRedSaludResponse retVal = ((MvcPrestadores.Services.SigmepOda.IServicioOrdenesAtencion)(this)).ObtenerOrdenesPagoRedSalud(inValue);
            totalRegistros = retVal.totalRegistros;
            totalValorPago = retVal.totalValorPago;
            return retVal.ObtenerOrdenesPagoRedSaludResult;
        }
        
        public System.Threading.Tasks.Task<MvcPrestadores.Services.SigmepOda.ObtenerOrdenesPagoRedSaludResponse> ObtenerOrdenesPagoRedSaludAsync(MvcPrestadores.Services.SigmepOda.ObtenerOrdenesPagoRedSaludRequest request) {
            return base.Channel.ObtenerOrdenesPagoRedSaludAsync(request);
        }
        
        public MvcPrestadores.Services.SigmepOda.ValoresConsultaMedica ObtenerValoresConsulta(string region, string codigoProducto, string codigoPlan, short nivelPrestadorDesde, short nivelPrestadorHasta) {
            return base.Channel.ObtenerValoresConsulta(region, codigoProducto, codigoPlan, nivelPrestadorDesde, nivelPrestadorHasta);
        }
        
        public System.Threading.Tasks.Task<MvcPrestadores.Services.SigmepOda.ValoresConsultaMedica> ObtenerValoresConsultaAsync(string region, string codigoProducto, string codigoPlan, short nivelPrestadorDesde, short nivelPrestadorHasta) {
            return base.Channel.ObtenerValoresConsultaAsync(region, codigoProducto, codigoPlan, nivelPrestadorDesde, nivelPrestadorHasta);
        }
        
        public string ObtenerUrlOda(long codigoContrato, int numeroOda, string tokenConfirmacion) {
            return base.Channel.ObtenerUrlOda(codigoContrato, numeroOda, tokenConfirmacion);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerUrlOdaAsync(long codigoContrato, int numeroOda, string tokenConfirmacion) {
            return base.Channel.ObtenerUrlOdaAsync(codigoContrato, numeroOda, tokenConfirmacion);
        }
    }
}
